<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <AssemblyName>Eclipse</AssemblyName>
        <RootNamespace>Eclipse</RootNamespace>
        <Version>0.1.0</Version>
        <Description>Eclipse: mod de Among Us con Mira API.</Description>
        <Authors>soyFault</Authors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AllOfUs.MiraAPI" Version="0.5.0" />
        <PackageReference Include="Reactor" Version="2.5.0-ci.371" />
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.735"
                          Private="false" ExcludeAssets="runtime;native" />
        <PackageReference Include="AmongUs.GameLibs.Steam" Version="2026.8.18"
                          PrivateAssets="all" />
        <PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.1.0-rc.1"
                          PrivateAssets="all" ExcludeAssets="runtime" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Options\" />
    </ItemGroup>

</Project>